### PR TITLE
Use Sidekiq::Process

### PR DESCRIPTION
**Pull request by iGEL**
This makes the code easier to read and relies on official Sidekiq APIs, which are less likely to break. It also only looks at the current process to see, whether it is still processing jobs, not any quieted process.

`identity` is inherited from `Sidekiq::Util`.

However, it relies on APIs added in Sidekiq 5

### CODE REVIEW

**Comment by BuonOmo** [comment]
This would mean removing support for Sidekiq 4.X. This means that we'll have to update our stack (@ccyrille). In the mean time 5.0 is out since April 2017, so it looks pretty safe to upgrade.

Otherwise, LGTM!

For later reviewers, the sidekiq process doc is available here: https://github.com/mperham/sidekiq/wiki/API#processes.

**Comment by pyrsmk** [comment]
Since the PR author is not responding, we're gonna stabilize the code in a new branch. Hence, this PR should be closed. @ccyrille

**Comment by BuonOmo** [comment]
@pyrsmk I think you could use this PR, committers from a repo are allowed to push to original fork branch. This would leave @iGEL's contribution to our git history, which seams more fair.

**Comment by pyrsmk** [comment]
@BuonOmo In fact, I couldn't find a way to pull the branch locally. I followed these steps to be able to do it : https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally#modifying-an-inactive-pull-request-locally

**Comment by BuonOmo** [comment]
Maybe he unchecked this option, that is unfortunate though :/

**Pull request merged**
